### ISSUE TITLE
Change type of vertexpos!

### ISSUE THREAD

**Issue by oskarddfa** [PIK-ICoNe/EmbeddedGraphs.jl#19]
In the definition of Embeddedgraph we should change the type of the vertexpos, because it is not good to leave it open for `Array{Any,N}`.
Maybe we could add another `T1 where T1<:AbstractFloat` to the definition of Embeddedgraphs, so that `T1` is the Type of the Vertexpos Array entries. 
I.e. `vertexpos::Array{T1, 2}` (or something similar) might make more sense instead of `vertexpos::Array` which is constructed into a `vertexpos::Array{Array{Any,1},1}`. 
Dunno if it breaks anything.

**Comment by luap-pik** [comment]
OK, sounds good. We could do sth like 
```
struct EmbeddedGraph{T1, T2} <: AbstractEmbeddedGraph{T1} where T1, T2
    graph::SimpleGraph{T1}
    vertexpos::Array{T2}
    distance::Function
end
```
although I'm not sure about where the `where` goes :-D
