### ISSUE TITLE
Random Geometric Graph function is super slow 

### ISSUE THREAD

**Issue by oskarddfa** [PIK-ICoNe/EmbeddedGraphs.jl#20]
We should change the design of the graph constructor for random geometric graphs. this way it is constructed in a super slow way (a complete graph is constructed and then the edges are deleted).

**Comment by luap-pik** [comment]
OK, what do you have in mind? I'm not sure which part makes it slow, since afaik construction of a complete graph should not be much slower then an empty graph.

**Comment by oskarddfa** [comment]
Sorry, I didn't get notified of your answer, I wrote it differently in a fast way, just need to push it

**Comment by oskarddfa** [comment]
I just pushed a new version for it. starting from a complete_graph and then deleting takes longer than starting with an empty graph and usually a sparse graph is desired anyways so that should be the way to go.

**Comment by luap-pik** [comment]
Cool! For curiosity, what is the benchmark of the two versions against each other? Would like to know how slow it was before :-D
